# Generated by Django 3.1.5 on 2021-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
